### ISSUE TITLE
Z390 GAMING X + 9700K

### ISSUE THREAD

**Issue by wrpota** [chrisyer/gigabyte-z390-gaming-x-hackintosh#1]
网卡是94360cd 现在没有安装显卡 怎么修改可以直接使用你这个EFI

**Comment by chrisyer** [comment]
直接使用config_UHD630.plist这个配置作为默认配置试试 @potaWang

**Comment by wrpota** [comment]
> 直接使用config_UHD630.plist这个配置作为替代配置试试@potaWang

使用那个之后 com.apple.driver.Kext ExcludeList v15.5.1 matches prelinked kext but can't determine if executables are the same (no UUIDs)' 'sophos anti-virus on access kext activated

**Comment by chrisyer** [comment]
你安装的Mac版本是什么？BIOS是什么版本的？

**Comment by wrpota** [comment]
> 你安装的Mac版本是什么？BIOS是什么版本的？

macos 目前使用的黑果小兵的10.14.6 双EFI版本的镜像安装的 bios版本 F8

**Comment by chrisyer** [comment]
我目前的版本是F7，是直接不进安装界面吗？能发下错误的截图吗？

**Comment by wrpota** [comment]
> 我当前的版本是F7，是直接不进安装界面吗？能发下错误的截图吗？

我是使用黑果小兵的镜像安装成功了之后核显无法驱动 板载usb没法驱动 换了你这个EFI之后启动就会卡在上面那个错误这里

**Comment by chrisyer** [comment]
可能是UUID & SMBIOS的原因，你把我的那个PLIST文件中UUID&SMBIOS信息用黑果小兵中UUID & SMBIOS的相关信息进行替换，不需要的删除试试

**Comment by wrpota** [comment]
> 可能是UUID & SMBIOS的原因，你把我的那个PLIST文件中UUID&SMBIOS信息用黑果小兵中UUID & SMBIOS的相关信息进行替换，不需要的删除试试

好的谢谢。。晚上回家试试

**Comment by wrpota** [comment]
> 可能是UUID & SMBIOS的原因，你把我的那个PLIST文件中UUID&SMBIOS信息用黑果小兵中UUID & SMBIOS的相关信息进行替换，不需要的删除试试
使用你的这个EFI 之后出现的问题 我已经把SMBIOS替换成黑果小兵的SMBIOS 只不过保留了iMac
![image](https://user-images.githubusercontent.com/21377464/68391389-78b9e580-01a2-11ea-9f3c-a5d10b670d1f.png)

**Comment by chrisyer** [comment]
![image](https://user-images.githubusercontent.com/14369492/68391988-bb2ff200-01a3-11ea-851d-ccdd763d8492.png)
这个部分删掉了吗，如果不行的话，将我的核显部分的patch替换到黑果小兵上，下列截图`PciRoot(0x0)/Pci(0x2,0x0)`是显卡的注入
![image](https://user-images.githubusercontent.com/14369492/68392083-f16d7180-01a3-11ea-82c5-23e2eaeb7045.png)

**Comment by wrpota** [comment]
> ![image](https://user-images.githubusercontent.com/14369492/68391988-bb2ff200-01a3-11ea-851d-ccdd763d8492.png)
> 这个部分删掉了吗，如果不行的话，将我的核显部分的patch替换到黑果小兵上，下列截图`PciRoot(0x0)/Pci(0x2,0x0)`是显卡的注入
> ![image](https://user-images.githubusercontent.com/14369492/68392083-f16d7180-01a3-11ea-82c5-23e2eaeb7045.png)

😂不弄了 先装win10用段时间 我白苹果是mojave 下不到原版的10.14.6  等10.15成熟了升级吧。。。正好到时候买一个5700XT 麻烦了

**Comment by chrisyer** [comment]
😂好吧
