### ISSUE TITLE
Cannot power off normally

### ISSUE THREAD

**Issue by Wen-He** [chrisyer/gigabyte-z390-gaming-x-hackintosh#2]
I'm also using Gigabyte Z390 GAMING X and i7-9700k and I'm struggling with a problem. When I shut down my computer, it comes out the following picture.

![WechatIMG1](https://user-images.githubusercontent.com/18651139/68537770-b6865c00-03a4-11ea-8144-cb79fd8c2d71.jpeg)

Do you know how to fix this?

[UPDATE]
The OS version is Catalina 10.15.1. It can boot normally.

**Comment by chrisyer** [comment]
Can you boot normally？

**Comment by Wen-He** [comment]
It can boot normally.

**Comment by chrisyer** [comment]
What‘s  the system version  you installed? Mojave, Catalina?

**Comment by Wen-He** [comment]
Sorry for missing details. I installed Catalina 10.15.1.

**Comment by chrisyer** [comment]
I didn‘t test it in Catalina，but maybe you can remove AppleALC.kext or update clover, lilu and other kext

**Comment by chrisyer** [comment]
or update clover, lilu and  other kext

**Comment by Wen-He** [comment]
Thank you for your suggestion. I will try it later. BTW, I happened to find a [solution](https://github.com/icymind/hackintosh/blob/master/post-installation-fix-restart-shutdown.md) related to this issue yesterday but I haven't tried it yet.
